#!/bin/bash

# 3-Clause BSD License
#
# Copyright (c) 2008-2023, James Philip Rowell,
# Alpha Eleven Incorporated
# www.alpha-eleven.com
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#  1. Redistributions of source code must retain the above copyright
#     notice, this list of conditions and the following disclaimer.
#
#  2. Redistributions in binary form must reproduce the above copyright
#     notice, this list of conditions and the following disclaimer in
#     the documentation and/or other materials provided with the
#     distribution.
#
#  3. Neither the name of the copyright holder, "Alpha Eleven, Inc.",
#     nor the names of its contributors may be used to endorse or
#     promote products derived from this software without specific prior
#     written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# test_expandseq - Run the expandseq regression tests.

usage_exit() {
    echo "Usage: ${0##*/} [-h | --help] [--testSystem-expandseq]"
    if [ "$1" = help ]; then
	cat - <<@eof

${0##*/} Run regression tests on expandseq. Must be run in the
<expandseq-repository>/tests directory.

Options:

 -h, --help         show this help and exit
 --testSystem-expandseq run the regression tests on the version of
                    expandseq installed on the system. Output test
                    results to appropriatly named file.

@eof
    fi
    exit 1
}

TEST_SYSTEM_EXPANDSEQ=no

#
# Parse options.  Stop when you get to the file list.
#
shopt -s extglob
while :
do
    case "$1" in
        -h|--help) usage_exit help
        ;;

        --testSystem-expandseq) TEST_SYSTEM_EXPANDSEQ=yes
             shift
        ;;

        --*|-*) usage_exit
        ;;

        *) break # We're done processing arguments, so let's get on with it. :-)
    esac
done

export LC_ALL=POSIX

# !!! This script MUST be run from the 'tests'
# !!! directory in the expandSeq git repo for this to work.
#
export TEST_DIR=`pwd`

if [[ `basename $TEST_DIR` != 'tests' ]]; then
    echo $0: error: not running from tests directory, aborted.
    exit 1
fi

unalias expandseq > /dev/null 2>&1
unalias condenseseq > /dev/null 2>&1
unalias rm > /dev/null 2>&1

tmpArgs=/tmp/tmpARGS_RENUM.$$
tmpfile=/tmp/tmpTEST_RENUM.$$

cleanup() {
    /bin/rm $tmpArgs > /dev/null 2>&1
    /bin/rm $tmpfile > /dev/null 2>&1
    exit 0
}

trap cleanup INT

TEST_OUT_FILENAME=test_expandseq.out.`uname`.new

trap cleanup INT

if [ "$TEST_SYSTEM_EXPANDSEQ" = no ]; then
    ln -sf ../expandseq/__main__.py  expandseq

    if [[ ! ":$PATH:" == *":$TEST_DIR:"* ]]; then
        export PATH="$TEST_DIR:$PATH"
    fi
else
    /bin/rm expandseq > /dev/null 2>&1
    /bin/rm condenseseq > /dev/null 2>&1
    TEST_OUT_FILENAME=test_expandseq.out.`uname`.installed.new
fi

echo "Test is using " `which expandseq`
echo "Test is using " `which condenseseq`

# The following are tests. One test per line.
# The first item on a line is the directory relative to
#     $TEST_DIR/testdir to run the test in.
# The second is the command to run.
# The rest are args to the command.
#
cat << EOF > $tmpArgs
expandseq                                # Run with no args - should do nothing
expandseq --version                      # MUST increment with each update/bug fix, corresp w/ release.
expandseq --help                         # To keep track of changes with help, plus check if correct
condenseseq                              # Run with no args - should do nothing
condenseseq --version                    # MUST increment with each update/bug fix, corresp w/ release.
condenseseq --help                       # To keep track of changes with help, plus check if correct
EOF

export NUM_TESTS=`wc -l < $tmpArgs`

echo ------ Begin Tests ------ > $TEST_DIR/$TEST_OUT_FILENAME

set -f # Turn off globbing
i=1
while true; do
    declare -a args=(`sed -n -e "$i p" $tmpArgs | sed -e 's/#.*//' `)
    if [ ${#args[@]} -eq 0 ]; then
        break;
    fi
    cmd=${args[0]}
    args=(${args[@]:1})
    echo "" >> $TEST_DIR/$TEST_OUT_FILENAME
    echo --- Test $i of $NUM_TESTS ---
    echo --- Test $i --- $cmd ${args[@]} --- >> $TEST_DIR/$TEST_OUT_FILENAME
    $cmd ${args[@]} >> $TEST_DIR/$TEST_OUT_FILENAME 2>&1
    i=$(expr $i + 1)
done
set +f # Turn globbing back on

cleanup
